POST localhost:8080/post-message
Content-Type: application/json

{"msg_id": "1234567890"}
###
POST localhost:8080/post-message/delay?millis=1000
###
GET localhost:8080/post-message/delay
###
###
###
GET localhost:8080/actuator
###
GET localhost:8080/actuator/health
###
GET localhost:8080/actuator/beans
###
GET localhost:8080/actuator/configprops
###
GET localhost:8080/actuator/configprops/spring.kafka
###
GET localhost:8080/actuator/env
###
GET localhost:8080/actuator/env/java.home
###
GET localhost:8080/actuator/conditions
###
GET localhost:8080/actuator/prometheus
###
###
GET localhost:8080/actuator/metrics
###
GET localhost:8080/actuator/metrics/application.started.time
###
GET localhost:8080/actuator/metrics/application.ready.time
###
GET localhost:8080/actuator/metrics/kafka.app.info.start.time.ms
###
###
GET localhost:8080/actuator/metrics/logback.events
###
GET localhost:8080/actuator/metrics/logback.events?tag=level:error
###
GET localhost:8080/actuator/metrics/logback.events?tag=level:warn
###
GET localhost:8080/actuator/metrics/logback.events?tag=level:info
###
GET localhost:8080/actuator/metrics/logback.events?tag=level:debug
###
GET localhost:8080/actuator/metrics/logback.events?tag=level:trace
###
###
GET localhost:8080/actuator/metrics/executor.active
###
GET localhost:8080/actuator/metrics/executor.completed
###
GET localhost:8080/actuator/metrics/executor.pool.core
###
GET localhost:8080/actuator/metrics/executor.pool.max
###
GET localhost:8080/actuator/metrics/executor.pool.size
###
GET localhost:8080/actuator/metrics/executor.queue.remaining
###
GET localhost:8080/actuator/metrics/executor.queued
###
###
GET localhost:8080/actuator/metrics/http.server.requests
###
GET localhost:8080/actuator/metrics/http.server.requests.active
###
###
GET localhost:8080/actuator/metrics/jvm.info
###
GET localhost:8080/actuator/metrics/jvm.buffer.count
###
GET localhost:8080/actuator/metrics/jvm.buffer.memory.used
###
GET localhost:8080/actuator/metrics/jvm.buffer.total.capacity
###
###
GET localhost:8080/actuator/metrics/jvm.classes.loaded
###
GET localhost:8080/actuator/metrics/jvm.classes.unloaded
###
GET localhost:8080/actuator/metrics/jvm.compilation.time
###
###
GET localhost:8080/actuator/metrics/jvm.memory.used?tag=area:nonheap
###
GET localhost:8080/actuator/metrics/jvm.memory.committed?tag=area:nonheap
###
GET localhost:8080/actuator/metrics/jvm.memory.max?tag=area:nonheap
###
GET localhost:8080/actuator/metrics/jvm.memory.usage.after.gc
###
###
GET localhost:8080/actuator/metrics/jvm.gc.live.data.size
###
GET localhost:8080/actuator/metrics/jvm.gc.max.data.size
###
GET localhost:8080/actuator/metrics/jvm.gc.memory.allocated
###
GET localhost:8080/actuator/metrics/jvm.gc.memory.promoted
###
GET localhost:8080/actuator/metrics/jvm.gc.overhead
###
GET localhost:8080/actuator/metrics/jvm.gc.pause
###
###
GET localhost:8080/actuator/metrics/jvm.threads.daemon
###
GET localhost:8080/actuator/metrics/jvm.threads.live
###
GET localhost:8080/actuator/metrics/jvm.threads.peak
###
GET localhost:8080/actuator/metrics/jvm.threads.started
###
GET localhost:8080/actuator/metrics/jvm.threads.states
###
GET localhost:8080/actuator/metrics/jvm.threads.states?tag=state:timed-waiting
###
GET localhost:8080/actuator/metrics/jvm.threads.states?tag=state:new
###
GET localhost:8080/actuator/metrics/jvm.threads.states?tag=state:runnable
###
GET localhost:8080/actuator/metrics/jvm.threads.states?tag=state:blocked
###
GET localhost:8080/actuator/metrics/jvm.threads.states?tag=state:waiting
###
GET localhost:8080/actuator/metrics/jvm.threads.states?tag=state:terminated
###
###
GET localhost:8080/actuator/metrics/process.cpu.time
###
GET localhost:8080/actuator/metrics/process.cpu.usage
###
GET localhost:8080/actuator/metrics/process.start.time
###
GET localhost:8080/actuator/metrics/process.uptime
###
###
GET localhost:8080/actuator/metrics/system.cpu.count
###
GET localhost:8080/actuator/metrics/system.cpu.usage
###
###
GET localhost:8080/actuator/metrics/disk.free
###
GET localhost:8080/actuator/metrics/disk.total
###
###
GET localhost:8080/actuator/metrics/jdbc.connections.active
###
GET localhost:8080/actuator/metrics/jdbc.connections.idle
###
GET localhost:8080/actuator/metrics/jdbc.connections.max
###
GET localhost:8080/actuator/metrics/jdbc.connections.min
###
###
GET localhost:8080/actuator/metrics/hikaricp.connections
###
GET localhost:8080/actuator/metrics/hikaricp.connections.acquire
###
GET localhost:8080/actuator/metrics/hikaricp.connections.creation
###
GET localhost:8080/actuator/metrics/hikaricp.connections.active
###
GET localhost:8080/actuator/metrics/hikaricp.connections.idle
###
GET localhost:8080/actuator/metrics/hikaricp.connections.max
###
GET localhost:8080/actuator/metrics/hikaricp.connections.min
###
GET localhost:8080/actuator/metrics/hikaricp.connections.pending
###
GET localhost:8080/actuator/metrics/hikaricp.connections.timeout
###
GET localhost:8080/actuator/metrics/hikaricp.connections.usage
###
###
GET localhost:8080/actuator/metrics/tomcat.sessions.active.current
###
GET localhost:8080/actuator/metrics/tomcat.sessions.active.max
###
GET localhost:8080/actuator/metrics/tomcat.sessions.alive.max
###
GET localhost:8080/actuator/metrics/tomcat.sessions.created
###
GET localhost:8080/actuator/metrics/tomcat.sessions.expired
###
GET localhost:8080/actuator/metrics/tomcat.sessions.rejected
###
###
GET localhost:8080/actuator/metrics/spring.kafka.template
###
GET localhost:8080/actuator/metrics/spring.kafka.listener
###
GET localhost:8080/actuator/metrics/kafka.consumer.commit.sync.time.ns.total
###
GET localhost:8080/actuator/metrics/kafka.consumer.committed.time.ns.total
###
GET localhost:8080/actuator/metrics/kafka.consumer.connection.close.rate
###
GET localhost:8080/actuator/metrics/kafka.consumer.connection.close.total
###
GET localhost:8080/actuator/metrics/kafka.consumer.connection.count
###
GET localhost:8080/actuator/metrics/kafka.consumer.connection.creation.rate
###
GET localhost:8080/actuator/metrics/kafka.consumer.connection.creation.total
###
GET localhost:8080/actuator/metrics/kafka.consumer.coordinator.assigned.partitions
###
GET localhost:8080/actuator/metrics/kafka.consumer.coordinator.commit.latency.avg
###
GET localhost:8080/actuator/metrics/kafka.consumer.coordinator.commit.latency.max
###
GET localhost:8080/actuator/metrics/kafka.consumer.coordinator.commit.rate
###
GET localhost:8080/actuator/metrics/kafka.consumer.coordinator.commit.total
###
GET localhost:8080/actuator/metrics/kafka.consumer.coordinator.failed.rebalance.rate.per.hour
###
GET localhost:8080/actuator/metrics/kafka.consumer.coordinator.failed.rebalance.total
###
GET localhost:8080/actuator/metrics/kafka.consumer.coordinator.heartbeat.rate
###
GET localhost:8080/actuator/metrics/kafka.consumer.coordinator.heartbeat.response.time.max
###
GET localhost:8080/actuator/metrics/kafka.consumer.coordinator.heartbeat.total
###
GET localhost:8080/actuator/metrics/kafka.consumer.coordinator.join.rate
###
GET localhost:8080/actuator/metrics/kafka.consumer.coordinator.join.time.avg
###
GET localhost:8080/actuator/metrics/kafka.consumer.coordinator.join.time.max
###
GET localhost:8080/actuator/metrics/kafka.consumer.coordinator.join.total
###
GET localhost:8080/actuator/metrics/kafka.consumer.coordinator.last.heartbeat.seconds.ago
###
GET localhost:8080/actuator/metrics/kafka.consumer.coordinator.last.rebalance.seconds.ago
###
GET localhost:8080/actuator/metrics/kafka.consumer.coordinator.partition.assigned.latency.avg
###
GET localhost:8080/actuator/metrics/kafka.consumer.coordinator.partition.assigned.latency.max
###
GET localhost:8080/actuator/metrics/kafka.consumer.coordinator.partition.lost.latency.avg
###
GET localhost:8080/actuator/metrics/kafka.consumer.coordinator.partition.lost.latency.max
###
GET localhost:8080/actuator/metrics/kafka.consumer.coordinator.partition.revoked.latency.avg
###
GET localhost:8080/actuator/metrics/kafka.consumer.coordinator.partition.revoked.latency.max
###
GET localhost:8080/actuator/metrics/kafka.consumer.coordinator.rebalance.latency.avg
###
GET localhost:8080/actuator/metrics/kafka.consumer.coordinator.rebalance.latency.max
###
GET localhost:8080/actuator/metrics/kafka.consumer.coordinator.rebalance.latency.total
###
GET localhost:8080/actuator/metrics/kafka.consumer.coordinator.rebalance.rate.per.hour
###
GET localhost:8080/actuator/metrics/kafka.consumer.coordinator.rebalance.total
###
GET localhost:8080/actuator/metrics/kafka.consumer.coordinator.sync.rate
###
GET localhost:8080/actuator/metrics/kafka.consumer.coordinator.sync.time.avg
###
GET localhost:8080/actuator/metrics/kafka.consumer.coordinator.sync.time.max
###
GET localhost:8080/actuator/metrics/kafka.consumer.coordinator.sync.total
###
GET localhost:8080/actuator/metrics/kafka.consumer.failed.authentication.rate
###
GET localhost:8080/actuator/metrics/kafka.consumer.failed.authentication.total
###
GET localhost:8080/actuator/metrics/kafka.consumer.failed.reauthentication.rate
###
GET localhost:8080/actuator/metrics/kafka.consumer.failed.reauthentication.total
###
GET localhost:8080/actuator/metrics/kafka.consumer.fetch.manager.bytes.consumed.rate
###
GET localhost:8080/actuator/metrics/kafka.consumer.fetch.manager.bytes.consumed.total
###
GET localhost:8080/actuator/metrics/kafka.consumer.fetch.manager.fetch.latency.avg
###
GET localhost:8080/actuator/metrics/kafka.consumer.fetch.manager.fetch.latency.max
###
GET localhost:8080/actuator/metrics/kafka.consumer.fetch.manager.fetch.rate
###
GET localhost:8080/actuator/metrics/kafka.consumer.fetch.manager.fetch.size.avg
###
GET localhost:8080/actuator/metrics/kafka.consumer.fetch.manager.fetch.size.max
###
GET localhost:8080/actuator/metrics/kafka.consumer.fetch.manager.fetch.throttle.time.avg
###
GET localhost:8080/actuator/metrics/kafka.consumer.fetch.manager.fetch.throttle.time.max
###
GET localhost:8080/actuator/metrics/kafka.consumer.fetch.manager.fetch.total
###
GET localhost:8080/actuator/metrics/kafka.consumer.fetch.manager.records.consumed.rate
###
GET localhost:8080/actuator/metrics/kafka.consumer.fetch.manager.records.consumed.total
###
GET localhost:8080/actuator/metrics/kafka.consumer.fetch.manager.records.lag.max
###
GET localhost:8080/actuator/metrics/kafka.consumer.fetch.manager.records.lead.min
###
GET localhost:8080/actuator/metrics/kafka.consumer.fetch.manager.records.per.request.avg
###
GET localhost:8080/actuator/metrics/kafka.consumer.incoming.byte.rate
###
GET localhost:8080/actuator/metrics/kafka.consumer.incoming.byte.total
###
GET localhost:8080/actuator/metrics/kafka.consumer.io.ratio
###
GET localhost:8080/actuator/metrics/kafka.consumer.io.time.ns.avg
###
GET localhost:8080/actuator/metrics/kafka.consumer.io.time.ns.total
###
GET localhost:8080/actuator/metrics/kafka.consumer.io.wait.ratio
###
GET localhost:8080/actuator/metrics/kafka.consumer.io.wait.time.ns.avg
###
GET localhost:8080/actuator/metrics/kafka.consumer.io.wait.time.ns.total
###
GET localhost:8080/actuator/metrics/kafka.consumer.io.waittime.total
###
GET localhost:8080/actuator/metrics/kafka.consumer.iotime.total
###
GET localhost:8080/actuator/metrics/kafka.consumer.last.poll.seconds.ago
###
GET localhost:8080/actuator/metrics/kafka.consumer.network.io.rate
###
GET localhost:8080/actuator/metrics/kafka.consumer.network.io.total
###
GET localhost:8080/actuator/metrics/kafka.consumer.node.incoming.byte.rate
###
GET localhost:8080/actuator/metrics/kafka.consumer.node.incoming.byte.total
###